version: '3'

services:
  mysql:
    image: docker.io/mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: kea
      MYSQL_USER: kea
      MYSQL_PASSWORD: kea
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:z
    healthcheck:
      test: [ "CMD-SHELL", 'mysqladmin ping' ]
      interval: 10s
      timeout: 2s
      retries: 10

  kea:
    build: ./kea-dhcp4
    depends_on:
      - mysql
    ports:
      - 6767:67

  kea-ca:
    build: ./kea-ca
    depends_on:
      - mysql
    ports:
      - 8000:8000
  #Monitoring
  #prometheus:
  #  image: docker.io/prom/prometheus
  #
  #mysql_exporter:
  #  image: docker.io/prom/mysqld-exporter
  #  depends_on:
  #    - mysql
  #
  #grafana:
  #  image: docker.io/grafana/grafana
  #  depends_on:
  #    - prometheus
